// firegrid-remediation-hardening.PUBLIC_SURFACES.5
// firegrid-architecture-boundary.SURFACE_AREA.1
//
// Curated substrate root. Raw kernel modules are available only from
// `@firegrid/substrate/kernel`. Server-side coordination (projection
// + work-claim + choreography) lives under `./coordination/`; the
// names re-exported here are unchanged.
export {
  EventStream,
  Operation,
  OperationHandle,
  type EventStreamDescriptor,
  type EventStreamDefinition,
  type OperationDefinition,
  type OperationDescriptor,
  type OperationHandleId,
} from "./descriptors/index.ts"

export {
  AwakeableToolInput,
  Choreography,
  ChoreographyLive,
  ChoreographyTimeout,
  ChoreographyTools,
  ChoreographyTrigger,
  CompletionId,
  CurrentWorkContext,
  MissingTriggerMatcherError,
  OwnerId,
  ProjectionMatchTrigger,
  Projection,
  ProjectionLive,
  ProjectionReadError,
  ProjectionWaitTimeout,
  ScheduleMeToolInput,
  SleepToolInput,
  TriggerMatchers,
  WaitForToolInput,
  Work,
  WorkClaim,
  WorkClaimError,
  WorkClaimLive,
  WorkId,
  currentWorkContextLayer,
  dispatchTrigger,
  triggerMatchersLayer,
  type ChoreographyLiveConfig,
  type ChoreographyOperation,
  type ChoreographyService,
  type ChoreographySuspension,
  type ChoreographyToolBinding,
  type ChoreographyToolBindings,
  type ChoreographyToolsConfig,
  type ClaimAttemptOutcome,
  type Claimed,
  type CurrentWorkContextValue,
  type Performed,
  type ProjectionLiveConfig,
  type ProjectionQuery,
  type ProjectionService,
  type Recorded,
  type ScheduleAtResult,
  type TriggerMatchEvaluation,
  type TriggerMatcher,
  type TriggerMatchersService,
  type WorkClaimLiveConfig,
  type WorkClaimService,
} from "./coordination/index.ts"
