import { randomUUID } from "node:crypto"

// firegrid-runtime-process.RUNTIME_PACKAGE.2
// firegrid-runtime-process.CONFIG_SURFACE.4
//
// Process identity is generated by default. Runtime identity is not
// normal user-facing environment config in v1; it can later be
// reified in durable runtime launch/liveness records. Explicit
// override is advanced/test usage only.
export const generateProcessId = (): string => `firegrid:${randomUUID()}`
