import { Effect } from "effect"
import { IdGen, IdGenLive } from "@firegrid/substrate/id-gen"

// firegrid-runtime-process.RUNTIME_PACKAGE.2
// firegrid-runtime-process.CONFIG_SURFACE.4
// firegrid-remediation-hardening.EFFECT_CONSISTENCY.5
// launchable-substrate-host.HOST_CONFIGURATION.7
//
// Process identity is generated by default. Runtime identity is not
// normal user-facing environment config in v1; it can later be
// reified in durable runtime launch/liveness records. Explicit
// override is advanced/test usage only.
//
// `generateProcessId` resolves through the kernel `IdGen` service
// rather than importing `node:crypto`, so identity generation stays
// portable. `IdGenLive` is provided here so the runtime composition
// does not need to thread an extra layer for the boot-time call.

export const generateProcessId: Effect.Effect<string> = Effect.gen(
  function* () {
    const idGen = yield* IdGen
    const uuid = yield* idGen.nextId
    return `firegrid:${uuid}`
  },
).pipe(Effect.provide(IdGenLive))
