import { randomUUID } from "node:crypto"

// launchable-substrate-host.HOST_CONFIGURATION.7
// Process identity is generated by default; explicit ids are advanced
// or test configuration. The default form is short enough for diagnostic
// readability and unique-enough for local development.
export const generateProcessId = (): string => `host:${randomUUID()}`
