// TODO(tf-8oaq): durable-table escape hatches below remain for documented
// advanced composition; Cycle 2 should replace or narrow them behind channels.
export {
  AppendError,
  Firegrid,
  FiregridConfig,
  FiregridConfigError,
  FiregridChannelError,
  FiregridControlPlaneTableLive,
  FiregridLive,
  FiregridRuntimeTables,
  FiregridStandaloneLive,
  LaunchInputError,
  PreloadError,
  firegridRuntimeTableTags,
  local,
  runtimeControlPlaneStreamUrl,
  type ClientOptions,
  type FiregridChannelMatch,
  type FiregridChannelsClient,
  type FiregridChannelWaitAnyInput,
  type FiregridChannelWaitAnyOutput,
  type FiregridChannelWaitOutput,
  type FiregridError,
  type FiregridPermissionsClient,
  type FiregridService,
  type FiregridSessionHandle,
  type FiregridSessionPermissionsClient,
  type FiregridSessionWaitClient,
  type FiregridSessionsClient,
  type FiregridWaitClient,
  type PromptInputError,
  type EventOffset,
  type RuntimeContextHandle,
  type RuntimeContextSnapshot,
} from "./firegrid.ts"
export {
  FiregridClientOperations,
  type PermissionRespondInput,
  type SessionCancelToolInput,
  type SessionCancelToolOutput,
  type SessionCloseToolInput,
  type SessionCloseToolOutput,
  type SessionPromptToolInput,
  type SessionPromptToolOutput,
} from "./operations.ts"
export {
  autoApproveSessionPermissions,
  type PermissionAutoApproveOptions,
  type PermissionAutoApprovePolicy,
  type PermissionAutoApproveSession,
} from "./permission-auto-approve.ts"
export type {
  PublicPromptRequest,
} from "@firegrid/protocol/runtime-ingress"
export type {
  AgentOutputEvent,
  FiregridSessionId,
  RuntimeAgentOutputEventPayload,
  RuntimeAgentOutputObservation,
  RuntimeContextId,
  RuntimePermissionOption,
  RuntimePermissionRequestObservation,
  SessionAgentOutputWaitInput,
  SessionAgentOutputWaitOutput,
  SessionAttachInput,
  SessionCreateOrLoadInput,
  SessionExternalKey,
  SessionHandlePromptInput,
  SessionPermissionRequestWaitInput,
  SessionPermissionRequestWaitOutput,
  SessionPermissionRespondInput,
} from "@firegrid/protocol/session-facade"
