import { describe, expect, it } from "vitest"
import { generateProcessId } from "../boot/identity.js"

// launchable-substrate-host.HOST_CONFIGURATION.7
// Process identity is generated by default; explicit ids are advanced
// or test configuration. The default form is unique per call and
// readable in diagnostic output.
describe("launchable-substrate-host.HOST_CONFIGURATION.7 — process identity is generated by default", () => {
  it("generateProcessId returns a non-empty string with the host: prefix", () => {
    const id = generateProcessId()
    expect(id.startsWith("host:")).toBe(true)
    expect(id.length).toBeGreaterThan("host:".length)
  })

  it("two consecutive generateProcessId calls return distinct ids", () => {
    expect(generateProcessId()).not.toBe(generateProcessId())
  })
})
