const table = (headers, rows) => {
  const escape = (value) => String(value).replaceAll("|", "\\|").replaceAll("\n", " ")
  return [
    `| ${headers.join(" | ")} |`,
    `| ${headers.map(() => "---").join(" | ")} |`,
    ...rows.map((row) => `| ${row.map(escape).join(" | ")} |`),
  ].join("\n")
}

export const renderMarkdown = (inventory) => {
  const roleRows = Object.entries(inventory.summary.byRole).map(([role, count]) => [
    role,
    count,
  ])
  const crossingRows = inventory.artifacts
    .filter((artifact) => artifact.boundaryCrossings.length > 0)
    .map((artifact) => [
      artifact.exportName,
      artifact.role,
      artifact.declarationLocation.path,
      artifact.exportLocation.path,
      artifact.boundaryCrossings
        .map((crossing) =>
          crossing.requirement
            ? `${crossing.kind}: ${crossing.from} -> ${crossing.to} (${crossing.requirement})`
            : `${crossing.kind}: ${crossing.from} -> ${crossing.to}`,
        )
        .join("; "),
    ])
  const effectRows = inventory.artifacts
    .filter((artifact) => artifact.effect !== null)
    .slice(0, 80)
    .map((artifact) => [
      artifact.exportName,
      artifact.declarationLocation.path,
      artifact.signature.typeParameters.map((param) => param.text).join(", "),
      artifact.signature.parameters
        .map((param) => `${param.rest ? "..." : ""}${param.name}: ${param.type}`)
        .join(", "),
      artifact.effect.success,
      artifact.effect.error,
      artifact.effect.requirement,
    ])

  return `# Effect Artifact Inventory

Generated by \`pnpm run arch:effect-artifacts\`.

ACIDs:

${inventory.acids.map((acid) => `- \`${acid}\``).join("\n")}

## Summary

- Total exported artifacts: ${inventory.summary.totalArtifacts}
- Effect-returning artifacts: ${inventory.summary.effectReturning}
- Re-exports: ${inventory.summary.reExports}
- Boundary crossings: ${inventory.summary.boundaryCrossings}

${table(["Role", "Count"], roleRows)}

## Boundary Crossings

${crossingRows.length === 0 ? "No package-boundary crossings detected." : table(["Export", "Role", "Declaration", "Exported From", "Crossing"], crossingRows)}

## Effect-Returning Exports

${effectRows.length === 0 ? "No exported Effect-returning artifacts detected." : table(["Export", "Declaration", "Type Parameters", "Parameters", "Success", "Error", "Requirement"], effectRows)}

Full structured inventory: \`docs/effect-artifact-inventory.json\`.
`
}
