import { rebuildProjection } from "@durable-agent-substrate/substrate"
import { Data, Effect } from "effect"
import { describe, expect, it } from "vitest"
import { FiregridRuntime, FiregridRuntimeBoot } from "../index.ts"

class RebuildProjectionFailed extends Data.TaggedError(
  "RebuildProjectionFailed",
)<{ readonly cause: unknown }> {}

// firegrid-runtime-process.RUNTIME_PACKAGE.2
// firegrid-runtime-process.DEV_ENV_INJECTION.1
// firegrid-runtime-process.DEV_ENV_INJECTION.2
// firegrid-runtime-process.DEV_ENV_INJECTION.3
// firegrid-runtime-process.DEV_ENV_INJECTION.6
//
// Embedded-dev mode launches a local DurableStreamTestServer for
// the duration of the FiregridRuntimeLive scope and pre-creates the
// substrate stream so reads find a valid endpoint. Scope
// finalization stops the embedded server.
describe("firegrid-runtime-process.DEV_ENV_INJECTION — embedded-dev mode launches a local Durable Streams endpoint", () => {
  it("embedded-dev creates a substrate stream at a resolved URL during the scope and tears down on finalization", async () => {
    await Effect.runPromise(
      Effect.scoped(
        Effect.gen(function* () {
          const runtime = yield* FiregridRuntime
          expect(runtime.bootMode).toBe("embedded-dev")
          expect(runtime.streamIdentity.streamName).toBe(
            "firegrid-test",
          )
          expect(runtime.streamIdentity.host).toBe("127.0.0.1")
          // OS-assigned port (port=0 → real port reflected on the
          // running server).
          expect(runtime.streamIdentity.port).toBeGreaterThan(0)
          // Within the scope, the substrate stream exists and a
          // rebuild succeeds (empty snapshot is acceptable).
          const snap = yield* Effect.tryPromise({
            try: () =>
              rebuildProjection({
                url: runtime.streamIdentity.streamUrl,
              }),
            catch: (cause) => new RebuildProjectionFailed({ cause }),
          })
          expect(snap.runs.size).toBe(0)
        }).pipe(
          Effect.provide(
            FiregridRuntimeBoot.embeddedDev({
              streamName: "firegrid-test",
            }),
          ),
        ),
      ),
    )
  })
})

// firegrid-runtime-process.CONFIG_SURFACE.4
// Process identity is generated by default and may be overridden
// for advanced/test usage.
describe("firegrid-runtime-process.CONFIG_SURFACE — process identity defaults are runtime-generated", () => {
  it("embedded-dev FiregridRuntime exposes a firegrid:-prefixed process id by default", async () => {
    const id = await Effect.runPromise(
      Effect.scoped(
        Effect.gen(function* () {
          const runtime = yield* FiregridRuntime
          return runtime.processId
        }).pipe(
          Effect.provide(
            FiregridRuntimeBoot.embeddedDev({ streamName: "id-default" }),
          ),
        ),
      ),
    )
    expect(id.startsWith("firegrid:")).toBe(true)
  })

  it("explicit processId overrides the generated identity (advanced/test usage)", async () => {
    const id = await Effect.runPromise(
      Effect.scoped(
        Effect.gen(function* () {
          const runtime = yield* FiregridRuntime
          return runtime.processId
        }).pipe(
          Effect.provide(
            FiregridRuntimeBoot.embeddedDev({
              streamName: "id-override",
              processId: "process-explicit",
            }),
          ),
        ),
      ),
    )
    expect(id).toBe("process-explicit")
  })
})
