import { Effect } from "effect"
import { describe, expect, it } from "vitest"
import { generateProcessId } from "../internal/identity.ts"

// firegrid-runtime-process.RUNTIME_PACKAGE.2
// firegrid-runtime-process.CONFIG_SURFACE.4
// firegrid-remediation-hardening.EFFECT_CONSISTENCY.5
//
// Runtime process identity is generated by default. The default
// form is unique per call and readable in diagnostic output. There
// is no FIREGRID_PROCESS_ID env knob in v1; explicit override is
// advanced/test usage only.
//
// Identity generation runs through the kernel `IdGen` service rather
// than a direct `node:crypto` import; `generateProcessId` self-provides
// `IdGenLive` so the runtime composition does not need to thread an
// extra layer for the boot-time call.
describe("firegrid-runtime-process.CONFIG_SURFACE — runtime process identity is generated by default", () => {
  it("generateProcessId returns a non-empty string with the firegrid: prefix", async () => {
    const id = await Effect.runPromise(generateProcessId)
    expect(id.startsWith("firegrid:")).toBe(true)
    expect(id.length).toBeGreaterThan("firegrid:".length)
  })

  it("two consecutive generateProcessId effects return distinct ids", async () => {
    const a = await Effect.runPromise(generateProcessId)
    const b = await Effect.runPromise(generateProcessId)
    expect(a).not.toBe(b)
  })
})
