import { describe, expect, it } from "vitest"
import { generateProcessId } from "../boot/identity.ts"

// firegrid-runtime-process.RUNTIME_PACKAGE.2
// firegrid-runtime-process.CONFIG_SURFACE.4
//
// Runtime process identity is generated by default. The default
// form is unique per call and readable in diagnostic output. There
// is no FIREGRID_PROCESS_ID env knob in v1; explicit override is
// advanced/test usage only.
describe("firegrid-runtime-process.CONFIG_SURFACE — runtime process identity is generated by default", () => {
  it("generateProcessId returns a non-empty string with the firegrid: prefix", () => {
    const id = generateProcessId()
    expect(id.startsWith("firegrid:")).toBe(true)
    expect(id.length).toBeGreaterThan("firegrid:".length)
  })

  it("two consecutive generateProcessId calls return distinct ids", () => {
    expect(generateProcessId()).not.toBe(generateProcessId())
  })
})
