flowchart LR

subgraph 0["packages"]
subgraph 1["client"]
subgraph 2["src"]
3["firegrid.ts"]
4["index.ts"]
end
end
subgraph 5["durable-streams"]
subgraph 6["src"]
7["DurableState.ts"]
8["DurableStreamLog.ts"]
9["log.ts"]
A["state.ts"]
end
end
subgraph B["protocol"]
subgraph C["src"]
subgraph D["launch"]
E["cursor.ts"]
F["helpers.ts"]
G["index.ts"]
H["schema.ts"]
I["state.ts"]
end
subgraph J["session"]
K["index.ts"]
L["schema.ts"]
M["state.ts"]
end
end
end
end
3-->9
3-->A
3-->G
4-->3
7-->G
7-->K
9-->8
A-->7
G-->E
G-->F
G-->H
G-->I
I-->H
K-->L
K-->M
M-->L
